chore(ci): temporarily disable migration tests

diff --git a/.github/workflows/acceptance-tests.yml b/.github/workflows/acceptance-tests.yml
--- a/.github/workflows/acceptance-tests.yml
+++ b/.github/workflows/acceptance-tests.yml
@@ -57,12 +57,15 @@ jobs:
         env:
           TF_ACC: 1
         continue-on-error: true
-      - name: Run Migration Tests
-        id: migration_tests
-        run: ./scripts/run-ci-tests migration
-        env:
-          TF_ACC: 1
-        continue-on-error: true
+      # - name: Run Migration Tests
+      #   id: migration_tests
+      #   run: ./scripts/run-ci-tests migration
+      #   env:
+      #     TF_ACC: 1
+      #   continue-on-error: true
+      # - name: Check Test Status
+      #   if: ${{ steps.acceptance_tests.outcome == 'failure' || steps.migration_tests.outcome == 'failure' }}
+      #   run: exit 1
       - name: Check Test Status
-        if: ${{ steps.acceptance_tests.outcome == 'failure' || steps.migration_tests.outcome == 'failure' }}
+        if: ${{ steps.acceptance_tests.outcome == 'failure' }}
         run: exit 1
